-- Demonstration lots aligned with the approved AGROMAL reference.
delete from public.lots where is_demo = true;

insert into public.lots (
  lot_number,
  animal_type,
  breed,
  region,
  quantity,
  weight_kg,
  feed_type,
  contract_type,
  contract_label,
  price,
  price_unit,
  price_note,
  primary_metric_label,
  primary_metric_value,
  secondary_metric_label,
  secondary_metric_value,
  tertiary_metric_label,
  tertiary_metric_value,
  status,
  status_note,
  action_note,
  is_demo
)
values
  (
    '001',
    'cattle',
    'Швицкая порода (Бычки)',
    'Чуйская область, Сокулукский район',
    24,
    10800,
    'Зерновой интенсивный откорм',
    'spot',
    'Разовая поставка — отгрузка 24 часа',
    630,
    'сом / кг',
    'в туше',
    'Средний убойный вес туши',
    '≈ 240 кг одной головы',
    null,
    null,
    null,
    null,
    'available',
    null,
    null,
    true
  ),
  (
    '002',
    'sheep',
    'Гиссарская порода (Молодые бараны)',
    'Чуйская область, Аламединский район',
    120,
    7200,
    'Предгорный нагул + докорм ячменем',
    'spot',
    'Разовая поставка — отгрузка 24 часа',
    660,
    'сом / кг',
    'в туше',
    'Средний убойный вес туши',
    '≈ 28 кг одной головы',
    null,
    null,
    null,
    null,
    'available',
    null,
    null,
    true
  ),
  (
    '003',
    'horse',
    'Новокиргизская порода (Кони на согым)',
    'Таласская область, Бакай-Атинский район',
    8,
    null,
    'Напольный докорм (Клевер + кукуруза)',
    'spot',
    'Разовая поставка — готовы к транспортировке',
    145000,
    'сомов',
    'за голову',
    'Упитанность',
    'Высшая (Казы — 4 пальца)',
    null,
    null,
    null,
    null,
    'available',
    null,
    null,
    true
  ),
  (
    '004',
    'selection',
    'Абердин-Ангус (Племенные быки-производители)',
    'Чуйская область, Ысык-Атинский район',
    2,
    null,
    null,
    'forward',
    'Селекционный выкуп / воспроизводство стада',
    320000,
    'сомов',
    'за голову',
    'Документы',
    'Племенные свидетельства, чипы ИСЖ, карты вакцинации',
    'Возраст / вес',
    '18 месяцев / живой вес ≈ 580 кг',
    null,
    null,
    'available',
    null,
    null,
    true
  ),
  (
    '005',
    'yak',
    'Высокогорный Топоз (Самцы на убой)',
    'Нарынская область, Ат-Башинский район (Высокогорные сырты)',
    35,
    12250,
    'Экологический высокогорный нагул',
    'forward',
    'Среднесрочный форвард — поставка октябрь 2026',
    580,
    'сом / кг',
    'в туше',
    null,
    null,
    null,
    null,
    null,
    null,
    'reserved',
    'ЛОТ ЗАБРОНИРОВАН',
    'ЛОТ ЗАБЛОКИРОВАН ДЛЯ ДРУГИХ УЧАСТНИКОВ',
    true
  ),
  (
    '006',
    'sheep',
    'Местная тонкорунная порода (Овцы / Токтолу)',
    'Нарынская область, Кочкорский район',
    150,
    null,
    null,
    'spot',
    'Разовая поставка',
    13200,
    'сомов',
    'за голову',
    null,
    null,
    null,
    null,
    null,
    null,
    'closed',
    'ТОРГИ ЗАКРЫТЫ — ЛОТ ВЫКУПЛЕН',
    'СДЕЛКА ЗАКРЫТА — КОНТРАГЕНТ ID: ***-094',
    true
  )
on conflict (lot_number) do update set
  animal_type = excluded.animal_type,
  breed = excluded.breed,
  region = excluded.region,
  quantity = excluded.quantity,
  weight_kg = excluded.weight_kg,
  feed_type = excluded.feed_type,
  contract_type = excluded.contract_type,
  contract_label = excluded.contract_label,
  price = excluded.price,
  price_unit = excluded.price_unit,
  price_note = excluded.price_note,
  primary_metric_label = excluded.primary_metric_label,
  primary_metric_value = excluded.primary_metric_value,
  secondary_metric_label = excluded.secondary_metric_label,
  secondary_metric_value = excluded.secondary_metric_value,
  tertiary_metric_label = excluded.tertiary_metric_label,
  tertiary_metric_value = excluded.tertiary_metric_value,
  status = excluded.status,
  status_note = excluded.status_note,
  action_note = excluded.action_note,
  is_demo = true;
